Portfolio mobile
Unyielding1/Portfolio-setup-and-mobile-version-skeleton pull request #1
Opened 2022-04-21 18:01 UTC by Unyielding1

this is my first page using HTML and CSS, I´m so proud and happy I think it is perfect

2022-04-21 21:18 UTC, Unyielding1 commented
I´m having this issue, I use visual studio limpers to clean all errors, but when I put my project in this limpers it says Error: Process completed with exit code 1. I don't know hot to fix this erros

2022-04-21 21:26 UTC, Unyielding1 commented
I know the limpers must be on a green but this error doesn't have a solution I think, I use this tool PostCSS Safe Parser to clean some part of the code, could that be the problem?

2022-04-21 22:08 UTC, OLIPLICHE reviewed
Hi <STUDENT_MENTION>, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that the Linter result is not green ✅ 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-04-21 22:22 UTC, Unyielding1 commented
ok, could you please tell me where can I find de PR thread?


El jue, 21 abr 2022 a las 17:08, Olipliche B.F. Mavoungou Paka (<
***@***.***>) escribió:

> ***@***.**** commented on this pull request.
>
> Hi <STUDENT_MENTION>,
>
> While you made a great effort in this project, unfortunately, I cannot
> proceed to review your code.
> Invalid Code Review Request
>
> You have submitted a project, that the Linter result is not green ✅
>
> Your Code Review Request will be marked as invalid in your Dashboard, so
> please submit a new one once you are ready 🙏
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me in your question so I can receive the
> notification.
>
> *Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.*
> ------------------------------
>
> *Invalid Code Review Request does not count into the code reviews limit.*
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Unyielding1/Portfolio-setup-and-mobile-version-skeleton/pull/1#pullrequestreview-949261895>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AXYQYI7DWMJSKEWITKCQBMTVGHGVDANCNFSM5T775WFA>
> .
> You are receiving this because you authored the thread.Message ID:
> <Unyielding1/Portfolio-setup-and-mobile-version-skeleton/pull/1/review/949261895
> @github.com>
>

2022-04-22 01:14 UTC, zainsadaqat requested changes
# Hello @Unyielding1 😃 😄 

You're doing a great job on your project. We're proud of you. Good job so far! 
# 👏🏻 👏🏻 👏🏻 

There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
  ✅  Correct use of Github Flow
  ✅  No linter errors

## Required Changes ♻️

- [ ] Please fix the background image as per the required figma design. As you can see
[Required Figma Design]
<img width="331" alt="Screen Shot 2022-04-22 at 5 52 29 AM" src="https://user-images.githubusercontent.com/83048208/164575757-62f6954e-a93f-4b4d-948e-4d3c3da35917.png">

- [ ] [Your Design]
<img width="317" alt="Screen Shot 2022-04-22 at 5 53 04 AM" src="https://user-images.githubusercontent.com/83048208/164575800-be7a6ae0-2992-4e74-bfc5-17c6c58f703a.png">

- [ ] [Required Navbar]
<img width="335" alt="Screen Shot 2022-04-22 at 6 01 00 AM" src="https://user-images.githubusercontent.com/83048208/164576316-06612ba6-6b50-4950-b2f4-8ae59d88f18c.png">

[Your Navbar]
- There's no need for the color gradient in the navbar as it's not in the requirements. Please remove one of them either Logo or your name from the navbar because there should be only one logo. Kindly fix this.
<img width="319" alt="Screen Shot 2022-04-22 at 6 01 34 AM" src="https://user-images.githubusercontent.com/83048208/164576353-9e78066a-4e46-4f1b-b873-53eadbc62b30.png">

_Check the comments under the review._


<img src="https://media0.giphy.com/media/QvMIzHw30MmMAqvOeo/giphy.gif"/>

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding! 👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-22 01:14 UTC, zainsadaqat commented on index.html
> +    <div>
Please use `<header>` tag to display the navbar.
#### Example
```
<header>
  <nav>
    Navbar Code ....
  </nav>
</header>
```

2022-04-22 01:14 UTC, zainsadaqat commented on index.html
> +  </div>
Please use `<ul>` `<li>` tags to display list of icons and use `<a>` for links.
#### Example
```
<ul>
  <li>
    <a href="github.com">
      <img src="github.jpg" alt=""/>
    </a>
  </li>
....
....
.....
</ul>
```

2022-04-22 01:14 UTC, zainsadaqat commented on index.html
>  </pre>
Please use `<p>` tag to display the paragraph for semantic reasons.

2022-04-22 01:14 UTC, zainsadaqat commented on index.html
> +you!
As this is the main heading for your Portfolio. this should be written in `<h1>` tag Kindly replace `<pre>` with `<h1>` and there should be only one `<h1>` tag per HTML document. 👍🏻

2022-04-22 01:14 UTC, zainsadaqat commented on index.html
> +  <h1> </h1>
Please remove the empty tag.

2022-04-22 01:14 UTC, zainsadaqat commented on index.html
> +  <title>Document</title>
Please rename it with your Project name 👍🏻

2022-04-22 17:52 UTC, merged